{% set version = "0.6.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vctrs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vctrs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vctrs/vctrs_{{ version }}.tar.gz
  sha256: 43167d2248fd699594044b5c8f1dbb7ed163f2d64761e08ba805b04e7ec8e402

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-glue                       # [build_platform != target_platform]
    - r-rlang >=1.0.2              # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.4.0
    - r-glue
    - r-rlang >=1.0.6
    - r-lifecycle >=1.0.3
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cli >=3.4.0
    - r-glue
    - r-rlang >=1.0.6
    - r-lifecycle >=1.0.3

test:
  commands:
    - $R -e "library('vctrs')"           # [not win]
    - "\"%R%\" -e \"library('vctrs')\""  # [win]

about:
  home: https://vctrs.r-lib.org/
  license: MIT
  summary: Defines new notions of prototype and size that are used to provide tools for consistent and well-founded type-coercion and size-recycling, and are in turn connected to ideas of type- and size-stability useful for analysing function interfaces.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: vctrs
# Title: Vector Helpers
# Version: 0.3.8
# Authors@R: c(person(given = "Hadley", family = "Wickham", role = "aut", email = "hadley@rstudio.com"), person(given = "Lionel", family = "Henry", role = c("aut", "cre"), email = "lionel@rstudio.com"), person(given = "Davis", family = "Vaughan", role = "aut", email = "davis@rstudio.com"), person(given = "data.table team", role = "cph", comment = "Radix sort based on data.table's forder() and their contribution to R's order()"), person(given = "RStudio", role = "cph"))
# Description: Defines new notions of prototype and size that are used to provide tools for consistent and well-founded type-coercion and size-recycling, and are in turn connected to ideas of type- and size-stability useful for analysing function interfaces.
# License: MIT + file LICENSE
# URL: https://vctrs.r-lib.org/
# BugReports: https://github.com/r-lib/vctrs/issues
# Depends: R (>= 3.3)
# Imports: ellipsis (>= 0.2.0), glue, rlang (>= 0.4.10)
# Suggests: bit64, covr, crayon, dplyr (>= 0.8.5), generics, knitr, pillar (>= 1.4.4), pkgdown, rmarkdown, testthat (>= 2.3.0), tibble, withr, xml2, waldo (>= 0.2.0), zeallot
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-GB
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2021-04-29 15:14:11 UTC; lionel
# Author: Hadley Wickham [aut], Lionel Henry [aut, cre], Davis Vaughan [aut], data.table team [cph] (Radix sort based on data.table's forder() and their contribution to R's order()), RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2021-04-29 16:00:03 UTC
